[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tml"
version = "0.1.0"
description = "Thoughtful Machine Learning"
keywords = ["datascience", "python"]

[project.urls]
homepage = "https://github.com/wilsonify/thoughtfulmachinelearning"

[tool.setuptools]
packages = ["tml"]