# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class HTTPValidationError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, detail=None):  # noqa: E501
        """HTTPValidationError - a model defined in OpenAPI

        :param detail: The detail of this HTTPValidationError.  # noqa: E501
        :type detail: object
        """
        self.openapi_types = {
            'detail': object
        }

        self.attribute_map = {
            'detail': 'detail'
        }

        self._detail = detail

    @classmethod
    def from_dict(cls, dikt) -> 'HTTPValidationError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HTTPValidationError of this HTTPValidationError.  # noqa: E501
        :rtype: HTTPValidationError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail(self):
        """Gets the detail of this HTTPValidationError.


        :return: The detail of this HTTPValidationError.
        :rtype: object
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this HTTPValidationError.


        :param detail: The detail of this HTTPValidationError.
        :type detail: object
        """

        self._detail = detail
