import logging
from dataclasses import dataclass
from typing import Optional, Callable, Union, Dict, List, Any

import pandas as pd
from joblib import Memory
from pycaret.loggers import BaseLogger

from s03_wine_fit.regression import DATAFRAME_LIKE, TARGET_LIKE, SEQUENCE_LIKE


@dataclass
class RegressionConfig():
    data_func: Optional[Callable[[], DATAFRAME_LIKE]] = None,
    target: TARGET_LIKE = -1,
    index: Union[bool, int, str, SEQUENCE_LIKE] = True,
    train_size: float = 0.7,
    test_data: Optional[DATAFRAME_LIKE] = None,
    ordinal_features: Optional[Dict[str, list]] = None,
    numeric_features: Optional[List[str]] = None,
    categorical_features: Optional[List[str]] = None,
    date_features: Optional[List[str]] = None,
    text_features: Optional[List[str]] = None,
    ignore_features: Optional[List[str]] = None,
    keep_features: Optional[List[str]] = None,
    preprocess: bool = True,
    create_date_columns: List[str] = ["day", "month", "year"],
    imputation_type: Optional[str] = "simple",
    numeric_imputation: Union[int, float, str] = "mean",
    categorical_imputation: str = "mode",
    iterative_imputation_iters: int = 5,
    numeric_iterative_imputer: Union[str, Any] = "lightgbm",
    categorical_iterative_imputer: Union[str, Any] = "lightgbm",
    text_features_method: str = "tf-idf",
    max_encoding_ohe: int = 25,
    encoding_method: Optional[Any] = None,
    rare_to_value: Optional[float] = None,
    rare_value: str = "rare",
    polynomial_features: bool = False,
    polynomial_degree: int = 2,
    low_variance_threshold: Optional[float] = None,
    group_features: Optional[dict] = None,
    drop_groups: bool = False,
    remove_multicollinearity: bool = False,
    multicollinearity_threshold: float = 0.9,
    bin_numeric_features: Optional[List[str]] = None,
    remove_outliers: bool = False,
    outliers_method: str = "iforest",
    outliers_threshold: float = 0.05,
    transformation: bool = False,
    transformation_method: str = "yeo-johnson",
    normalize: bool = False,
    normalize_method: str = "zscore",
    pca: bool = False,
    pca_method: str = "linear",
    pca_components: Optional[Union[int, float, str]] = None,
    feature_selection: bool = False,
    feature_selection_method: str = "classic",
    feature_selection_estimator: Union[str, Any] = "lightgbm",
    n_features_to_select: Union[int, float] = 0.2,
    transform_target: bool = False,
    transform_target_method: str = "yeo-johnson",
    custom_pipeline: Optional[Any] = None,
    custom_pipeline_position: int = -1,
    data_split_shuffle: bool = True,
    data_split_stratify: Union[bool, List[str]] = False,
    fold_strategy: Union[str, Any] = "kfold",
    fold: int = 10,
    fold_shuffle: bool = False,
    fold_groups: Optional[Union[str, pd.DataFrame]] = None,
    n_jobs: Optional[int] = -1,
    use_gpu: bool = False,
    html: bool = True,
    session_id: Optional[int] = None,
    system_log: Union[bool, str, logging.Logger] = True,
    log_experiment: Union[bool, str, BaseLogger, List[Union[str, BaseLogger]]] = False,
    experiment_name: Optional[str] = None,
    experiment_custom_tags: Optional[Dict[str, Any]] = None,
    log_plots: Union[bool, list] = False,
    log_profile: bool = False,
    log_data: bool = False,
    verbose: bool = True,
    memory: Union[bool, str, Memory] = True,
    profile: bool = False,
    profile_kwargs: Optional[Dict[str, Any]] = None,
