# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PredictWsOutput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ws_pred=None, composite_desire=None):  # noqa: E501
        """PredictWsOutput - a model defined in OpenAPI

        :param ws_pred: The ws_pred of this PredictWsOutput.  # noqa: E501
        :type ws_pred: object
        :param composite_desire: The composite_desire of this PredictWsOutput.  # noqa: E501
        :type composite_desire: object
        """
        self.openapi_types = {
            'ws_pred': object,
            'composite_desire': object
        }

        self.attribute_map = {
            'ws_pred': 'ws_pred',
            'composite_desire': 'composite_desire'
        }

        self._ws_pred = ws_pred
        self._composite_desire = composite_desire

    @classmethod
    def from_dict(cls, dikt) -> 'PredictWsOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The predict_ws_output of this PredictWsOutput.  # noqa: E501
        :rtype: PredictWsOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ws_pred(self):
        """Gets the ws_pred of this PredictWsOutput.


        :return: The ws_pred of this PredictWsOutput.
        :rtype: object
        """
        return self._ws_pred

    @ws_pred.setter
    def ws_pred(self, ws_pred):
        """Sets the ws_pred of this PredictWsOutput.


        :param ws_pred: The ws_pred of this PredictWsOutput.
        :type ws_pred: object
        """

        self._ws_pred = ws_pred

    @property
    def composite_desire(self):
        """Gets the composite_desire of this PredictWsOutput.


        :return: The composite_desire of this PredictWsOutput.
        :rtype: object
        """
        return self._composite_desire

    @composite_desire.setter
    def composite_desire(self, composite_desire):
        """Sets the composite_desire of this PredictWsOutput.


        :param composite_desire: The composite_desire of this PredictWsOutput.
        :type composite_desire: object
        """

        self._composite_desire = composite_desire
