# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PredictWsInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, product_stock=None, price=None, prod_alcohol_percent_percent=None, js=None, ww=None, d=None, bh=None, ws=None, we=None, rp=None, jd=None, sj=None, v=None, cg=None, tp=None):  # noqa: E501
        """PredictWsInput - a model defined in OpenAPI

        :param product_stock: The product_stock of this PredictWsInput.  # noqa: E501
        :type product_stock: object
        :param price: The price of this PredictWsInput.  # noqa: E501
        :type price: object
        :param prod_alcohol_percent_percent: The prod_alcohol_percent_percent of this PredictWsInput.  # noqa: E501
        :type prod_alcohol_percent_percent: object
        :param js: The js of this PredictWsInput.  # noqa: E501
        :type js: object
        :param ww: The ww of this PredictWsInput.  # noqa: E501
        :type ww: object
        :param d: The d of this PredictWsInput.  # noqa: E501
        :type d: object
        :param bh: The bh of this PredictWsInput.  # noqa: E501
        :type bh: object
        :param ws: The ws of this PredictWsInput.  # noqa: E501
        :type ws: object
        :param we: The we of this PredictWsInput.  # noqa: E501
        :type we: object
        :param rp: The rp of this PredictWsInput.  # noqa: E501
        :type rp: object
        :param jd: The jd of this PredictWsInput.  # noqa: E501
        :type jd: object
        :param sj: The sj of this PredictWsInput.  # noqa: E501
        :type sj: object
        :param v: The v of this PredictWsInput.  # noqa: E501
        :type v: object
        :param cg: The cg of this PredictWsInput.  # noqa: E501
        :type cg: object
        :param tp: The tp of this PredictWsInput.  # noqa: E501
        :type tp: object
        """
        self.openapi_types = {
            'product_stock': object,
            'price': object,
            'prod_alcohol_percent_percent': object,
            'js': object,
            'ww': object,
            'd': object,
            'bh': object,
            'ws': object,
            'we': object,
            'rp': object,
            'jd': object,
            'sj': object,
            'v': object,
            'cg': object,
            'tp': object
        }

        self.attribute_map = {
            'product_stock': 'productStock',
            'price': 'price',
            'prod_alcohol_percent_percent': 'prodAlcoholPercent_percent',
            'js': 'JS',
            'ww': 'WW',
            'd': 'D',
            'bh': 'BH',
            'ws': 'W&amp;S',
            'we': 'WE',
            'rp': 'RP',
            'jd': 'JD',
            'sj': 'SJ',
            'v': 'V',
            'cg': 'CG',
            'tp': 'TP'
        }

        self._product_stock = product_stock
        self._price = price
        self._prod_alcohol_percent_percent = prod_alcohol_percent_percent
        self._js = js
        self._ww = ww
        self._d = d
        self._bh = bh
        self._ws = ws
        self._we = we
        self._rp = rp
        self._jd = jd
        self._sj = sj
        self._v = v
        self._cg = cg
        self._tp = tp

    @classmethod
    def from_dict(cls, dikt) -> 'PredictWsInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The predict_ws_input of this PredictWsInput.  # noqa: E501
        :rtype: PredictWsInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_stock(self):
        """Gets the product_stock of this PredictWsInput.


        :return: The product_stock of this PredictWsInput.
        :rtype: object
        """
        return self._product_stock

    @product_stock.setter
    def product_stock(self, product_stock):
        """Sets the product_stock of this PredictWsInput.


        :param product_stock: The product_stock of this PredictWsInput.
        :type product_stock: object
        """

        self._product_stock = product_stock

    @property
    def price(self):
        """Gets the price of this PredictWsInput.


        :return: The price of this PredictWsInput.
        :rtype: object
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this PredictWsInput.


        :param price: The price of this PredictWsInput.
        :type price: object
        """

        self._price = price

    @property
    def prod_alcohol_percent_percent(self):
        """Gets the prod_alcohol_percent_percent of this PredictWsInput.


        :return: The prod_alcohol_percent_percent of this PredictWsInput.
        :rtype: object
        """
        return self._prod_alcohol_percent_percent

    @prod_alcohol_percent_percent.setter
    def prod_alcohol_percent_percent(self, prod_alcohol_percent_percent):
        """Sets the prod_alcohol_percent_percent of this PredictWsInput.


        :param prod_alcohol_percent_percent: The prod_alcohol_percent_percent of this PredictWsInput.
        :type prod_alcohol_percent_percent: object
        """

        self._prod_alcohol_percent_percent = prod_alcohol_percent_percent

    @property
    def js(self):
        """Gets the js of this PredictWsInput.


        :return: The js of this PredictWsInput.
        :rtype: object
        """
        return self._js

    @js.setter
    def js(self, js):
        """Sets the js of this PredictWsInput.


        :param js: The js of this PredictWsInput.
        :type js: object
        """

        self._js = js

    @property
    def ww(self):
        """Gets the ww of this PredictWsInput.


        :return: The ww of this PredictWsInput.
        :rtype: object
        """
        return self._ww

    @ww.setter
    def ww(self, ww):
        """Sets the ww of this PredictWsInput.


        :param ww: The ww of this PredictWsInput.
        :type ww: object
        """

        self._ww = ww

    @property
    def d(self):
        """Gets the d of this PredictWsInput.


        :return: The d of this PredictWsInput.
        :rtype: object
        """
        return self._d

    @d.setter
    def d(self, d):
        """Sets the d of this PredictWsInput.


        :param d: The d of this PredictWsInput.
        :type d: object
        """

        self._d = d

    @property
    def bh(self):
        """Gets the bh of this PredictWsInput.


        :return: The bh of this PredictWsInput.
        :rtype: object
        """
        return self._bh

    @bh.setter
    def bh(self, bh):
        """Sets the bh of this PredictWsInput.


        :param bh: The bh of this PredictWsInput.
        :type bh: object
        """

        self._bh = bh

    @property
    def ws(self):
        """Gets the ws of this PredictWsInput.


        :return: The ws of this PredictWsInput.
        :rtype: object
        """
        return self._ws

    @ws.setter
    def ws(self, ws):
        """Sets the ws of this PredictWsInput.


        :param ws: The ws of this PredictWsInput.
        :type ws: object
        """

        self._ws = ws

    @property
    def we(self):
        """Gets the we of this PredictWsInput.


        :return: The we of this PredictWsInput.
        :rtype: object
        """
        return self._we

    @we.setter
    def we(self, we):
        """Sets the we of this PredictWsInput.


        :param we: The we of this PredictWsInput.
        :type we: object
        """

        self._we = we

    @property
    def rp(self):
        """Gets the rp of this PredictWsInput.


        :return: The rp of this PredictWsInput.
        :rtype: object
        """
        return self._rp

    @rp.setter
    def rp(self, rp):
        """Sets the rp of this PredictWsInput.


        :param rp: The rp of this PredictWsInput.
        :type rp: object
        """

        self._rp = rp

    @property
    def jd(self):
        """Gets the jd of this PredictWsInput.


        :return: The jd of this PredictWsInput.
        :rtype: object
        """
        return self._jd

    @jd.setter
    def jd(self, jd):
        """Sets the jd of this PredictWsInput.


        :param jd: The jd of this PredictWsInput.
        :type jd: object
        """

        self._jd = jd

    @property
    def sj(self):
        """Gets the sj of this PredictWsInput.


        :return: The sj of this PredictWsInput.
        :rtype: object
        """
        return self._sj

    @sj.setter
    def sj(self, sj):
        """Sets the sj of this PredictWsInput.


        :param sj: The sj of this PredictWsInput.
        :type sj: object
        """

        self._sj = sj

    @property
    def v(self):
        """Gets the v of this PredictWsInput.


        :return: The v of this PredictWsInput.
        :rtype: object
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this PredictWsInput.


        :param v: The v of this PredictWsInput.
        :type v: object
        """

        self._v = v

    @property
    def cg(self):
        """Gets the cg of this PredictWsInput.


        :return: The cg of this PredictWsInput.
        :rtype: object
        """
        return self._cg

    @cg.setter
    def cg(self, cg):
        """Sets the cg of this PredictWsInput.


        :param cg: The cg of this PredictWsInput.
        :type cg: object
        """

        self._cg = cg

    @property
    def tp(self):
        """Gets the tp of this PredictWsInput.


        :return: The tp of this PredictWsInput.
        :rtype: object
        """
        return self._tp

    @tp.setter
    def tp(self, tp):
        """Sets the tp of this PredictWsInput.


        :param tp: The tp of this PredictWsInput.
        :type tp: object
        """

        self._tp = tp
