openapi: 3.0.0
info:
  title: Wine Observer
  version: 0.1.0

paths:
  /items/:
    $ref: "paths/items/items.yaml"
  /predict:
    $ref: "paths/predict/predict.yaml"
  /ui/token:
    $ref: "paths/token/token.yaml"
  /users/me/:
    $ref: "paths/users/me/me.yaml"
  /users/me/items/:
    $ref: "paths/users/me/items/items.yaml"

components:
  schemas:
    Body_login_for_access_token_token_post:
      $ref: "components/schemas/Body_login_for_access_token_token_post.yaml"
    HTTPValidationError:
      $ref: "components/schemas/HTTPValidationError.yaml"
    Token:
      $ref: "components/schemas/Token.yaml"
    User:
      $ref: "components/schemas/User.yaml"
    ValidationError:
      $ref: "components/schemas/ValidationError.yaml"
  securitySchemes:
    OAuth2PasswordBearer:
      $ref: "components/securitySchemes/OAuth2PasswordBearer.yaml"
