FROM tml-wine-base:latest
ADD . /app
WORKDIR /app
RUN apt-get update -y && \
    apt-get install -y  \
    gcc g++ gfortran  \
    python3-dev python3-pip python3-setuptools
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 10
RUN grep -vE '^#' apt-requirements.txt | xargs apt-get install -y
RUN pip install -r requirements.txt
