FROM python:3.8-buster
WORKDIR /app
ADD . /app
RUN apt-get update -y && apt-get install -y gcc g++ gfortran
RUN grep -vE '^#' apt-requirements.txt | xargs apt-get install -y
RUN pip install -r requirements.txt
